config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'observations#index'
  resources :observations
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'twilio/sms' => 'twilio#sms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :user, foreign_key: :created_by
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :observations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  before_action :authenticate_user!, except: [:index]

  after_action :verify_authorized, unless: :devise_controller? 
  rescue_from Pundit::NotAuthorizedError do |e|
    flash[:danger] = "NO!"
    redirect_to "/"
  end

  skip_after_action :verify_authorized, only: [:index, :new, :show, :create]

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :phone) }
  end


  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_observation, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_authorized, only: [:index, :new, :show, :create, :destroy]
  skip_before_filter  :verify_authenticity_token

  def index
    @observations = Observation.all
  end

  def show
    @observation = Observation.find(params[:id])
  end


  def new
    @observation = Observation.new
  end

  def edit
    @observation = Observation.find(params[:id])
    authorize @observation
  end

  def create
    @observation = Observation.new(observation_params)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    @observation = Observation.find(params[:id])

    authorize @observation

    respond_to do |format|
      if @observation.update(description: params[:description], pic: params[:pic])
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url, notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
    # authorize @observation
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_observation
    @observation = Observation.find(params[:id])
    # authorize @observation
  end

  def observation_params
    params.require(:observation).permit(:phone, :created_by, :sighted_at, :description, :pic)
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ActionController::Base 
  # after_filter :set_header 
  # skip_before_action :verify_authenticity_token 
  # skip_after_action :verify_authorized

  # skip_before_filter  :verify_authenticity_token

  def sms
    description = params["Body"]
    picture = params["MediaUrl0"]
    location = params["FromZip"]
    number = params["From"]

    user = User.find_by(phone: number)

    if user

      Observation.create!(created_by: user.id, sighted_at: Time.now, description: description,pic: picture, phone: number)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WildDurham" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <img id="wilddurham" src="wilddurham.png" >
          <ul style="font-size:20px" class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path)  %></li>
              <li><%= link_to("Register", new_user_registration_path(User.new))  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/row-->

        <footer>
        <%# <p>&copy; Company 2016</p> %>
        </footer>

      </div> <!-- /container -->

    </body>
  </html>

app/views/observations/_form.html.erb
<%= form_for(@observation) do |f| %>
  <% if @observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>

        <% @observation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# <%= f.hidden_field :created_by, value: current_user.id %1> %>
  <%# <%= f.hidden_field :phone value: current_user.phone %1> %>
  <% if policy(@observation).update?%>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :pic %><br>
      <%= f.text_area :pic %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/observations/edit.html.erb
<h1>Edit Observation</h1>

<%= render 'form' %>

 <%= link_to 'Back', root_path  %>

app/views/observations/index.html.erb
<div id='sightings' class='jumbotron'>
  <h2><strong>Sightings:</strong></h2>
  <p>Text a picture and description to (919)289-8440 or: </p>
  <%= link_to 'Post Here', new_observation_path(@observation), class: "btn btn-default btn-primary"  %>
</div>

<div id='observations' class='jumbotron'>
  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr text-align=center>
        <th>Sighted At</th>
        <th>Description</th>
        <th>Pic</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @observations.each do |obs| %>
        <tr class='entry' > 
          <td><%= obs.sighted_at.strftime("%m/%d/%y %H:%M UTC")%></td>
          <td><%= obs.description%></td>
          <td><%= obs.user.id %></td>
          <td>  <% if !obs.pic.nil? %>
              <img height=200px width=auto src=<%= obs.pic%>>
            <% end %>
          </td>
          <td>  <% if policy(obs).update?%>
              <%= link_to 'Edit', edit_observation_path(obs), class: "btn btn-default btn-primary"  %>
              <%= link_to 'Delete', obs, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-primary" %>
            <% end %>
          </td>

        </tr>
      <% end %>
    </tbody>


  </table>
</div>

app/views/observations/new.html.erb
<div class="jumbotron">
  <h4> New Sighting</h4>
  <%= bootstrap_form_for @observation, url: observations_path(@observation) do |f| %>
    <%= f.text_field :description %>
    <%= f.text_area :pic %>
    <%= f.hidden_field :created_by, value: current_user.id %>
    <%= f.hidden_field :sighted_at, value: Time.now %>
    <%= f.hidden_field :phone, value: current_user.phone %>
    <button class="btn btn-primary">Submit</button>
  <% end %>

  <%= link_to 'Back', root_path  %>
</div>

app/views/observations/show.html.erb
<h1>Observation updated!</h1>
<div id='observations' class='jumbotron'>
  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr text-align=center>
        <th>Sighted At</th>
        <th>Description</th>
        <th>Pic</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <tr class='entry'> 
        <td><%= @observation.sighted_at.strftime("%m/%d/%y %H:%M UTC")%></td>
        <td><%= @observation.description%></td>
        <td>  <% if !@observation.pic.nil? %>
            <img height=200px width=auto src=<%= @observation.pic%>>
          </td>
          <td>
              <%= link_to 'Edit', edit_observation_path(@observation), class: "btn btn-default btn-primary"  %>
            <%= link_to 'Delete', @observation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-primary" %>
          </td>

        </tr>
      <% end %>
    </tbody>


  </table>
  <%= link_to 'Back', root_path, class: "btn btn-default btn-primary"  %>
</div>